FROM node:14-buster

RUN apt update && apt install -y \
  libnss3 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libdbus-1-3 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  libgbm1 \
  libasound2 \
  libxshmfence1 \
  chromium

RUN mkdir /tests
WORKDIR /tests
ADD ./E2eTests ./

RUN npm install

CMD ["npx", "codeceptjs", "run"]
