FROM node:14-buster

RUN useradd -d /app -m -r -s /bin/bash app-user
WORKDIR /app
ADD ./Applications/client ./

RUN npm install
RUN npx next build

EXPOSE 3000
USER app-user
CMD ["npx", "next", "start"]
