version: "3"
services:
  applications_client:
    build:
      context: .
      dockerfile: Dockerfile.Applications.client
  xvfb:
    image: metal3d/xvfb
    entrypoint: ["Xvfb", ":1", "-ac", "-listen", "tcp"]
  e2e_test:
    build:
      context: .
      dockerfile: Dockerfile.E2eTests
    environment:
      CODECEPT_URL: http://applications_client:3000
      XDISPLAY: xvfb:1.0
    volumes:
      - ./output:/tests/output
    depends_on:
      - xvfb
